### ISSUE TITLE
python3.10: error while loading shared libraries: libpython3.10.so.1.0

### ISSUE THREAD

**Issue by wishrohitv** [EchterAlsFake/PySide6-to-Android#1]
log - 100%|████████████████████████████████████████████████████| 812765.0/812765.0 [11:37<00:00, 1165.89it/s]
+ export HOST_ARCH=aarch64-linux-android
+ HOST_ARCH=aarch64-linux-android
+ export TOOLCHAIN=/home/wishrohitv/Android/Sdk/ndk/25c/toolchains/llvm/prebuilt/linux-x86_64/bin
+ TOOLCHAIN=/home/wishrohitv/Android/Sdk/ndk/25c/toolchains/llvm/prebuilt/linux-x86_64/bin
+ export TOOL_PREFIX=/home/wishrohitv/Android/Sdk/ndk/25c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android
+ TOOL_PREFIX=/home/wishrohitv/Android/Sdk/ndk/25c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android
+ export PLATFORM_API=29
+ PLATFORM_API=29
+ export CXX=/home/wishrohitv/Android/Sdk/ndk/25c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android29-clang++
+ CXX=/home/wishrohitv/Android/Sdk/ndk/25c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android29-clang++
+ export 'CPP=/home/wishrohitv/Android/Sdk/ndk/25c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android29-clang++ -E'
+ CPP='/home/wishrohitv/Android/Sdk/ndk/25c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android29-clang++ -E'
+ export AR=/home/wishrohitv/Android/Sdk/ndk/25c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar
+ AR=/home/wishrohitv/Android/Sdk/ndk/25c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar
+ export RANLIB=/home/wishrohitv/Android/Sdk/ndk/25c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib
+ RANLIB=/home/wishrohitv/Android/Sdk/ndk/25c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib
+ export CC=/home/wishrohitv/Android/Sdk/ndk/25c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android29-clang
+ CC=/home/wishrohitv/Android/Sdk/ndk/25c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android29-clang
+ export LD=/home/wishrohitv/Android/Sdk/ndk/25c/toolchains/llvm/prebuilt/linux-x86_64/bin/ld
+ LD=/home/wishrohitv/Android/Sdk/ndk/25c/toolchains/llvm/prebuilt/linux-x86_64/bin/ld
+ export READELF=/home/wishrohitv/Android/Sdk/ndk/25c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-readelf
+ READELF=/home/wishrohitv/Android/Sdk/ndk/25c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-readelf
+ export 'CFLAGS=-fPIC -DANDROID'
+ CFLAGS='-fPIC -DANDROID'
+ ./configure --host=aarch64-linux-android --target=aarch64-linux-android --build=x86_64-pc-linux-gnu --enable-shared --enable-ipv6 ac_cv_file__dev_ptmx=yes ac_cv_file__dev_ptc=no --without-ensurepip ac_cv_little_endian_double=yes
checking for git... found
checking build system type... x86_64-pc-linux-gnu
checking host system type... aarch64-unknown-linux-android
checking for python3.10... python3.10
checking for python interpreter for cross build... python3.10: error while loading shared libraries: libpython3.10.so.1.0: cannot open shared object file: No such file or directory
configure: error: python3.10 interpreter not found
(venv) [wishrohitv@archlinux pyside-setup]$

log file - 
[logfile.txt](https://github.com/EchterAlsFake/PySide6-to-Android/files/14568379/logfile.txt)

**Comment by EchterAlsFake** [comment]
Hi, you just need to type this in your terminal:

export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

**Comment by wishrohitv** [comment]
> Hi, you just need to type this in your terminal:
> 
> export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
> 
> 

I already ran this, 
Question - if only wheels are required for building apk then your wheels will work for me, in my computer?

**Comment by EchterAlsFake** [comment]
I am not quite sure about this but you could try it. Look into my Porn Fetch project. There are the aarch64 wheels for PySide 6.6.1 and Shiboken 6.6.1.

Look in src/backend or something. But I don't know if this really works.

But if it works, please let me know, so I could provide them as a release asset in this repository.

**Comment by wishrohitv** [comment]
i tried by your wheels but getting this error even though i kept wheels in correct directory
![Screenshot from 2024-03-13 11-20-41](https://github.com/EchterAlsFake/PySide6-to-Android/assets/126248971/9e8ebaff-3d96-4895-83b1-72a7492072b1)

**Comment by EchterAlsFake** [comment]
You are using PySide 6.6.1 and Shiboken 6.6.1 and you have Qt 6.6.1 installed right?

**Comment by wishrohitv** [comment]
> You are using PySide 6.6.1 and Shiboken 6.6.1 and you have Qt 6.6.1 installed right?

oh sorry by default pip installed 6.6.2 version , i followed your git repo instruction also don't know qt version

**Comment by EchterAlsFake** [comment]
Okay, so first try to install PySide6.6.1 by doing:

`pip install PySide6=6.6.1 Shiboken==6.6.1`

If you then still get the error try installing Qt 6.6.1. You do this by downloading the qt unified installer from qt.io. When running the installer you should somewhere be able to select Qt 6.6.1. Make sure to install Android and Desktop (GCC) but only of the first step with the pip package doesn't fix the issue.

**Comment by wishrohitv** [comment]
> Okay, so first try to install PySide6.6.1 by doing:
> 
> `pip install PySide6=6.6.1 Shiboken==6.6.1`
> 
> If you then still get the error try installing Qt 6.6.1. You do this by downloading the qt unified installer from qt.io. When running the installer you should somewhere be able to select Qt 6.6.1. Make sure to install Android and Desktop (GCC) but only of the first step with the pip package doesn't fix the issue.

thanks for your valuable time man, sorry for wasting your time i'm getting error while installing qt installer
```
[wishrohitv@archlinux Downloads]$ ./qt-unified-linux-x64-4.7.0-online.run 
./qt-unified-linux-x64-4.7.0-online.run: error while loading shared libraries: libxcb-icccm.so.4: cannot open shared object file: No such file or directory

``` sorry i'm windows user

**Comment by EchterAlsFake** [comment]
Hi, sorry for the late reply.

Fixing missing shared libraries is generally really easy. You just need to install a certain package. Just google it like "error while loading shared libraries: libxcb-icccm.so.4: cannot open shared object file: No such file or directory" and you will find a result.

But I don't understand why the Qt wheels don't work for you. Qt is only needed for building I guess so you are using a different PySide or Shiboken version or your environment is somehow broken. 

Can you create a new virtual environment like

`python3 -m venv venv`
`source venv/bin/activate`

and then do: `pip install PySide6==6.6.1 Shiboken6=6.6.1` and try it again?

If your application just crashes the error is related to something different, but if the build process itself is successful this would be great.

I have compiled the Qt wheels on Ubuntu and copied them to my Arch Linux system and they worked too, so idk.

**Comment by wishrohitv** [comment]
thanks for your answer, i did the same as you mentioned above but i got this error - 
![Screenshot from 2024-03-19 15-46-31](https://github.com/EchterAlsFake/PySide6-to-Android/assets/126248971/7c594107-a39d-4595-9f45-ac20b4e94e61)
i don't use qml but got this 

i did google for xcb binaries those are for Ubuntu installation i tried to install them using pacman didn't work
if you have any guide for pyside android deploy ubuntu then please tell me process and how to solve ```compiler cannot create executable```

**Comment by wishrohitv** [comment]
> i tried your wheels but giving me error -
> 
> ![Screenshot from 2024-03-13 11-40-46](https://private-user-images.githubusercontent.com/126248971/312330713-b58fbb3d-558d-480d-a1c5-a1131c410ba0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NjE3MDAsIm5iZiI6MTcxMDg2MTQwMCwicGF0aCI6Ii8xMjYyNDg5NzEvMzEyMzMwNzEzLWI1OGZiYjNkLTU1OGQtNDgwZC1hMWM1LWExMTMxYzQxMGJhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQxNTE2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OWNiNjlhOTk4ZTY3OTA5MGU4Yzg1NjliM2MxMmY5YzMxMTgxNzlkMWFhZjVmZjhiOTczYjZkZmVhMTRiNWU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gYDVCaJTq_qO4Nz3WKpJ9lAgVRdMQWqKMmbA_4xCf8Y)

thank you so much again, i got this previous error again - complete log
[logfile.txt](https://github.com/EchterAlsFake/PySide6-to-Android/files/14652687/logfile.txt)

**Comment by EchterAlsFake** [comment]
Okay I have an idea... When installing the Android NDK and SDK, did you use the install script from this repo which had its last commit 3 months ago or did you use the install script which is directly in this README? Because the old script is out dated. You would need to use the README for installing. I need to update this later.

**Comment by wishrohitv** [comment]
ok now this time i installed via readme, but got this new type of error - 
```Using Android NDK: /home/gitpod/Android/Sdk/ndk/25c
Using Android SDK: /home/gitpod/Android/Sdk
File buildozer.spec created, ready to customize!
WARNING:root:[DEPLOY] Qt plugin folder 'accessiblebridge' does not exist or is not a directory for this Android platform
WARNING:root:[DEPLOY] Qt plugin folder 'platforms_darwin' does not exist or is not a directory for this Android platform
WARNING:root:[DEPLOY] Qt plugin folder 'xcbglintegrations' does not exist or is not a directory for this Android platform
WARNING:root:[DEPLOY] Qt plugin folder 'platformthemes' does not exist or is not a directory for this Android platform
WARNING:root:[DEPLOY] Qt plugin folder 'platforminputcontexts' does not exist or is not a directory for this Android platform
WARNING:root:[DEPLOY] Qt plugin folder 'generic' does not exist or is not a directory for this Android platform
WARNING:root:[DEPLOY] Qt plugin folder 'egldeviceintegrations' does not exist or is not a directory for this Android platform
# Check configuration tokens
Traceback (most recent call last):
  File "/workspace/pyside6-to-apk/venv/bin/buildozer", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/workspace/pyside6-to-apk/venv/lib/python3.12/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/workspace/pyside6-to-apk/venv/lib/python3.12/site-packages/buildozer/__init__.py", line 1018, in run_command
    targets = [x[0] for x in self.targets()]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/pyside6-to-apk/venv/lib/python3.12/site-packages/buildozer/__init__.py", line 910, in targets
    m = __import__('buildozer.targets.{0}'.format(target),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/pyside6-to-apk/venv/lib/python3.12/site-packages/buildozer/targets/android.py", line 40, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'
Exception occurred: Traceback (most recent call last):
  File "/workspace/pyside6-to-apk/venv/lib/python3.12/site-packages/PySide6/scripts/deploy_lib/commands.py", line 24, in run_command
    subprocess.check_call(command, shell=is_windows)
  File "/home/gitpod/.pyenv/versions/3.12.2/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['buildozer', 'android', 'debug']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/pyside6-to-apk/venv/lib/python3.12/site-packages/PySide6/scripts/android_deploy.py", line 163, in main
    Buildozer.create_executable(config.mode)
  File "/workspace/pyside6-to-apk/venv/lib/python3.12/site-packages/PySide6/scripts/deploy_lib/android/buildozer.py", line 354, in create_executable
    run_command(command=command, dry_run=Buildozer.dry_run)
  File "/workspace/pyside6-to-apk/venv/lib/python3.12/site-packages/PySide6/scripts/deploy_lib/commands.py", line 30, in run_command
    raise RuntimeError(
RuntimeError: [DEPLOY] Command buildozer android debug failed with error Command '['buildozer', 'android', 'debug']' returned non-zero exit status 1. and return_code1
```
and thank for time again

**Comment by wishrohitv** [comment]
thank again, i managed to compile in apk successfully with your wheels, but apk is not installing on android👵, i tested with arch64 based devices

**Comment by EchterAlsFake** [comment]
Hi, what do you mean with not installing?  Just not installing or not opening? 

If it's not installing you should see an error message from Android why it's not installing. If it's not opening please use the Android Studio to get the logs from your application.

**Comment by wishrohitv** [comment]
thanks i will try again, nowadays I'm busy in college assignments

**Comment by EchterAlsFake** [comment]
- You can use Python 3.11, but you need to have 3.10 installed for building the wheels.

Although 3.11 support was recently added and I don't know if it works.

**Comment by EchterAlsFake** [comment]
So everything is stable now and I hope you will get it working with my pre-compiled wheels.

I close this now, but feel free to reopen it, if you need additional help :)
