### ISSUE TITLE
Android SDK / NDK

### ISSUE THREAD

**Issue by MomenAshraf5** [EchterAlsFake/PySide6-to-Android#2]
after write this 

wget -O - "https://raw.githubusercontent.com/EchterAlsFake/PySide6-to-Android/master/android_sdk_ndk_script.sh" | bash

in the last terminal cant determine the path

Error: Could not determine SDK root.
Error: Either specify it explicitly with --sdk_root= or move this package into its expected location: <sdk>/cmdline-tools/latest/
Android SDK and NDK installation completed.

**Comment by EchterAlsFake** [comment]
Yes, this is currently not an issue. I will fix that later, but you should still be able to compile everything.

**Comment by MomenAshraf5** [comment]
> Yes, this is currently not an issue. I will fix that later, but you should still be able to compile everything.
yes  it's fine 
but now the file buildozer.spec dont see my photo i have folder images when 
i put extension but not work to open image 
source.include.exts = png, jpg
source,include.patterns = images/*.png 
the image all is png but when i install apk on my phone 
are you have solution for this ?
to add image 
i have main.qml and main.py

**Comment by EchterAlsFake** [comment]
Unfortunately I didn't work with images yet, so I can't assist you with that.

**Comment by EchterAlsFake** [comment]
Since the script isn't needed anymore and the reason why this issue was opened is therefore gone, I close this now :)
